export const TASKS = {
  ADD_TASK: 'ADD_TASK',
  ADD_TASKS: 'ADD_TASKS',
  ADD_CAT: 'ADD_CAT',
  ADD_SOLV: 'ADD_SOLV',
  ADD_TEMP: 'ADD_TEMP',
  ADD_PRESS: 'ADD_PRESS',
  ADD_MODEL: 'ADD_MODEL',
  ADD_CML_BASE64: 'ADD_CML_BASE64',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASKS: 'DELETE_TASKS',
  EDIT_TASK: 'EDIT_TASK',
  ADD_AMOUNT: 'ADD_AMOUNT',
  ADD_MODEL_ERR: 'ADD_MODEL_ERR',
  ADD_SOLV_ERR: 'ADD_SOLV_ERR',
  CHECK_TASK: 'CHECK_TASK',
  SELECT_ALL_TASKS: 'SELECT_ALL_TASKS',
  DESELECT_ALL_TASKS: 'DESELECT_ALL_TASKS',
  DELETE_SELECTED_TASKS: 'DELETE_SELECTED_TASKS',
  DELETE_ALL_TASKS: 'DELETE_ALL_TASKS',
  ADD_SELECTED_TASK_CONDITION: 'ADD_SELECTED_TASK_CONDITION',
};
export const TRIGGER = 'TRIGGER';
export const TRIGGER_MODAL_FILE_UPLOAD = 'TRIGGER_MODAL_FILE_UPLOAD';
export const TRIGGER_MODAL_CONDITION_SELECT = 'TRIGGER_MODAL_CONDITION_SELECT';
export const SOLVENT = 'SOLVENT';
export const CATALYST = 'CATALYST';
